### PR TITLE
A dark mode button

### PR DESCRIPTION
**Pull request by dubeyji10**
added a simple dark mode button

todo1

todo2

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for your PR, @dubeyji10 , but I don't think we should do this. It adds complexity to the example that isn't relevant to the point of the example, which is to show the IndexedDB APIs.

I did see that someone filed an issue about the colors: https://github.com/mdn/to-do-notifications/issues/9 and I agree with that, and would accept a much smaller PR that changes the colors to less aggressive ones :).

**Comment by dubeyji10** [comment]
yeah i get it it doesn't have anything to do with the example i'm sorry  😅
( i will change colors to something relaxing like green or maybe a royal purple )

**Comment by wbamberg** [comment]
No need to be sorry @dubeyji10 . Thanks for your contribution :).

**Comment by teoli2003** [comment]
Closing per previous comments.

**Pull request closed without merging**
