### PR TITLE
Remove innerHTML from to-do app

### PR DESCRIPTION
**Pull request by wbamberg**
This is a piece of https://github.com/mdn/content/issues/13496, and removes `innerHTML` usage from the to-do app. This app is used pretty extensively in the IndexedDB documentation on MDN, so this change should enable us to remove lots of usages of `innerHTML` from our docs.

I've intentionally kept the scope just to this change.

### CODE REVIEW

**Review by teoli2003 — APPROVED** [review]
Death to innerHTML

**Comment by teoli2003** [comment]
I don't have the right to merge this. @Rumyra or @ddbeck, can you merge this? (And, eventually, give me the rights here)

**Comment by wbamberg** [comment]
Thanks @teoli2003 ! We should also consider transferring this example to dom-examples.

**Comment by Rumyra** [comment]
That's quite a bit of `innerHTML` 😳

**Pull request merged**
